### PR TITLE
Added Emoticons

### PR DESCRIPTION
**Pull request by sathishsundar78**
HI Sir, I added emoticons as a new feature. Kindly review and approve the pull request and merge to the product

### CODE REVIEW

**Comment by sathishsundar78** [comment]
Pull request has created

**Comment by sathishsundar78** [comment]
thanks your pull request has approved.

**Review by sathishgith — APPROVED** [review]
Code has no issue.

**Comment by sathishgith** [comment]
Merging it from sathishgith

**Pull request merged**
